// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package database

import (
	"database/sql"
)

type Rating struct {
	ID          int64
	Workkey     string
	Editionkey  sql.NullString
	Ratingvalue sql.NullInt64
	Datestamp   sql.NullString
}

type Reading struct {
	ID         int64
	Workkey    string
	Editionkey sql.NullString
	Shelf      sql.NullString
	Datestamp  sql.NullString
}
